config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'
  get '/api' => 'pages#api'

  namespace :api do
    jsonapi_resources :projects
  end

  get 'issues/:id' => 'issues#show', as: :issue

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/confirm' => 'projects#confirm', as: :project_confirm
  post 'projects' => 'projects#create', as: :projects
  get 'projects' => 'projects#index', as: :project_index
  get 'projects/:id' => 'projects#show', as: :project

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/search', to: 'search#index', as: :project_search
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'

  get '/:user' => 'users#show', as: :user
  match '/:user/:repo', to: 'projects#show', via: [:get], as: :project_direct, constraints: { repo: /[^\/]+/ }

  root 'projects#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @projects = Project
                .search(params[:q])
                .for_language(params[:main_language])
                .paginate(page: params[:page])
  end
end

app/views/search/index.html.erb
<div class='row'>
  <div class='col-md-8'>
    <%= render @projects %>
  </div>

  <div class='col-md-4 hidden-xs hidden-sm'>
    <span><%= t('.filter_by_language') %></span>

    <%= form_tag(project_search_path, method: :get, enforce_utf8: false) do %>
      <%= hidden_field_tag :q, params[:q] %>
      <ul>
        <% @projects.map(&:main_language).compact.uniq.each_with_index do |language, index| %>
          <li>
            <%= check_box_tag 'main_language[]', language, params.fetch(:main_language, []).include?(language) , id: "main_language_#{index}" %>
            <%= label_tag "main_language_#{index}", language %>
          </li>
        <% end %>
      </ul>

      <%= submit_tag t('.submit'), name: nil, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>