config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'
  get '/api' => 'pages#api'

  namespace :api do
    jsonapi_resources :projects
  end

  get 'issues/:id' => 'issues#show', as: :issue

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/confirm' => 'projects#confirm', as: :project_confirm
  post 'projects' => 'projects#create', as: :projects
  get 'projects' => 'projects#index', as: :project_index
  get 'projects/:id' => 'projects#show', as: :project

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/search', to: 'search#index', as: :project_search
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'

  get '/:user' => 'users#show', as: :user
  match '/:user/:repo', to: 'projects#show', via: [:get], as: :project_direct, constraints: { repo: /[^\/]+/ }

  root 'projects#index'
end

app/models/user.rb
class User < ApplicationRecord
  def self.create_from_auth_hash(hash)
    create!(AuthHash.new(hash).user_info)
  end

  def to_s
    nickname
  end

  def to_param
    nickname
  end

  def assign_from_auth_hash(hash)
    # do not update the email address in case the user has updated their
    # email prefs and used a new email
    ignored_fields = %i(email name blog location)
    update(AuthHash.new(hash).user_info.except(*ignored_fields))
  end

  def self.find_by_auth_hash(hash)
    conditions = AuthHash.new(hash).user_info.slice(:provider, :uid)
    where(conditions).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_nickname(params[:user])
    if @user
      @projects = Project.where('lower(owner) = lower(?)', params[:user]).order('score desc, last_scored desc')
    else
      redirect_to '/'
    end
  end
end

app/views/users/show.html.erb
<div class='row'>
  <div class='col-md-8'>
    <h1>
      <% if @user == current_user %>
        <%= t('.my_projects') %>
      <% else %>
        <%= t('.users_projects', user: @user.nickname) %>
      <% end %>
    </h1>
    <% if @projects.any? %>
      <%= link_to t('.add_a_project'), new_project_path %>
      <%= render @projects %>
    <% else %>
      <p>
        <%= t('.no_projects', user: @user.nickname) %>
        <%= link_to t('.add_a_project'), new_project_path %>
      </p>
    <% end %>
  </div>
</div>