config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'
  get '/api' => 'pages#api'

  namespace :api do
    jsonapi_resources :projects
  end

  get 'issues/:id' => 'issues#show', as: :issue

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/confirm' => 'projects#confirm', as: :project_confirm
  post 'projects' => 'projects#create', as: :projects
  get 'projects' => 'projects#index', as: :project_index
  get 'projects/:id' => 'projects#show', as: :project

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/search', to: 'search#index', as: :project_search
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'

  get '/:user' => 'users#show', as: :user
  match '/:user/:repo', to: 'projects#show', via: [:get], as: :project_direct, constraints: { repo: /[^\/]+/ }

  root 'projects#index'
end

app/views/pages/about.html.erb
<div class="col-xs-12 col-md-8">
  <h2><%= t('.what') %></h2>

  <p><%= t('.inspired_html', link: link_to('24pullrequests', 'https://github.com/24pullrequests/24pullrequests')) %></p>

  <h3><%= t('.scoring') %></h3>
  <p><%= t('.projects_scored') %></p>

  <h3><%= t('.how') %></h3>
  <p><%= t('.contribulator_html', link: link_to('Contribulator', 'https://github.com/24pullrequests/contribulator')) %></p>

  <p><%= t('.help_html', link: link_to('gitter', 'https://gitter.im/24pullrequests/contribulator')) %></p>

  <p><%= t('.track_html', languages: @languages.to_sentence) %></p>

</div>

<div class="col-md-4 hidden-xs hidden-md">
  <%= render @project %>
<% if @issue %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title"><%= t('.can_you_help') %> '<%= link_to @issue.title, @issue.url %>'?</h4>
    </div>
    <div class="panel-body">

      <%== parse_markdown(@issue.body) %>

      <% labels = @issue.labels %>
      <% if labels %>
        <ul class="issue-labels list-inline">
          <% labels.each do |label| %>
            <li class="issue-label" style="background-color: #<%= label[:color] %>">
              <strong><%= link_to label[:name], label[:url] %></strong>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if @issue.comments > 0 %>
        <p class="text-success"><%= link_to "#{@issue.comments} #{t('.replies')}", @issue.url %></p>
      <% else %>
        <p class="text-warning"><%= link_to t('.no_replies'), @issue.url %></p>
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/pages/api.html.erb
<h2>JSON API</h2>

<p>Follows the <%= link_to '{ json:api }', 'http://jsonapi.org/' %> spec.</p>

<h3>GET Projects</h3>

<pre><code>curl <%= api_projects_url %></code></pre>

<p>Sort by scores</p>

<pre><code>curl <%= api_projects_url(sort: '-score') %></code></pre>

<pre><code>{
  "data": [
    {
      "id": "6673802",
      "type": "projects",
      "links": {
        "self": "<%= api_project_url(6673802) %>"
      },
      "attributes": {
        "owner": "24pullrequests",
        "name": "24pullrequests",
        "name-with-owner": "24pullrequests/24pullrequests",
        "github-id": 6673802,
        "score": 38
      }
    }
  ],
  "meta": {
    "total-records": 1
  },
  "links": {
    "first": "<%= api_projects_url %>?page%5Bnumber%5D=1&page%5Bsize%5D=50",
    "last": "<%= api_projects_url %>?page%5Bnumber%5D=1&page%5Bsize%5D=50"
  }
}</code></pre>

<h3>GET Project</h3>

<p>The project ID is the github repository ID.</p>

<pre><code>curl <%= api_project_url(6673802) %></code></pre>

<pre><code>{
  "data": {
    "id": "6673802",
    "type": "projects",
    "links": {
      "self": "<%= api_project_url(6673802) %>"
    },
    "attributes": {
      "owner": "24pullrequests",
      "name": "24pullrequests",
      "name-with-owner": "24pullrequests/24pullrequests",
      "github-id": 6673802,
      "score": 38
    }
  }
}</code></pre>