config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'
  get '/api' => 'pages#api'

  namespace :api do
    jsonapi_resources :projects
  end

  get 'issues/:id' => 'issues#show', as: :issue

  get 'projects/new' => 'projects#new', as: :new_project
  get 'projects/confirm' => 'projects#confirm', as: :project_confirm
  post 'projects' => 'projects#create', as: :projects
  get 'projects' => 'projects#index', as: :project_index
  get 'projects/:id' => 'projects#show', as: :project

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/search', to: 'search#index', as: :project_search
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'

  get '/:user' => 'users#show', as: :user
  match '/:user/:repo', to: 'projects#show', via: [:get], as: :project_direct, constraints: { repo: /[^\/]+/ }

  root 'projects#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= t('.tab_title') %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <a class="forkme" href="https://github.com/24pullrequests/contribulator">
      <img alt="Fork me on GitHub" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png"/>
    </a>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to t('.header_title'), root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= form_tag projects_path, class: 'navbar-form' do |f| %>
                <%= text_field_tag 'project[github_url]', '', placeholder: t('github_url'), class: 'form-control' %>
                <%= submit_tag t('.search'), class: 'btn btn-default' %>
              <% end %>
            </li>
            <% if logged_in? %>
              <li><%= link_to current_user, current_user %></li>
              <li><%= link_to t('.log_out'), logout_path %></li>
            <% else %>
              <li><%= link_to t('.log_in'), login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container notices">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible"><%= value %></div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <div class='row'>
          <div class="col-md-6 col-xs-6"><%= t('.project_count', count: Project.count) %></div>
          <div class="col-md-6 col-xs-6 text-right"><%= link_to t('.about_this'), about_path %></div>
        </div>
      </div>
    </footer>
  </body>
</html>